In [1]:
# This is how we comment nad below is how we print
print ("Hello, World!")

Hello, World!


In [2]:
# for loop
max=5
for i in range(5):
    print (i)

0
1
2
3
4


In [27]:
# iterating over list elements
print ("List of hurricanes in 2019.")
list_name=["Barry","Dorian","Humberto", "Jerry","Lorenzo", "Pablo"]
for idx, name in enumerate(list_name): #notice the colon at the end
    print (idx+1, name) #because index starts from zero in python

List of hurricanes in 2019.
1 Barry
2 Dorian
3 Humberto
4 Jerry
5 Lorenzo
6 Pablo


In [14]:
a = [1, 2, 3, 4, 5, 6]
print(a*4)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [15]:
import numpy as np

In [16]:
a = np.array(a)
print(a*2)

[ 2  4  6  8 10 12]


In [10]:
np.zeros? # use tab to get the prompt

In [18]:
a_reshaped = a.reshape(3,2)
print(a_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
# Sum of array elements
print (np.sum(a_reshaped,axis=0)) # Sum of elements along axis 0, that means sum collums data
print (a_reshaped.sum(axis=1))    # sum of elements alont axis 1, that means sum rows data
print (a_reshaped.sum())          # Sum of all elements

[ 9 12]
[ 3  7 11]
21


In [33]:
# Other basic math functions
print (a_reshaped.max(axis=1))
print(a_reshaped[0:2,1])

[2 4 6]
[2 4]


---
### Numpy masked arrays
* For doing numpy like operations on arrays with missing or invalid values
* Operations with masked arrays generally slower than numpy.ndarray
* A masked array has two componenents
    * numpy.ndarray
    * mask
    
For details refer:
https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

In [36]:
import numpy.ma as ma

# leats mask values smaller or equal to 2
masked_a = ma.masked_array(a, mask=[1, 1, 0, 0, 0, 0]) # 0 means no mask
print(masked_a)

[-- -- 3 4 5 6]


In [42]:
print(a)
# Create mask using conditions
masked_a2 = ma.masked_where(a<=2, a)
print(masked_a2)

[1 2 3 4 5 6]
[-- -- 3 4 5 6]


In [44]:
ma.masked_where?

In [46]:
print(a[a<5])
for aaa in masked_a2:
    print(aaa)

[1 2 3 4]
--
--
3
4
5
6


In [47]:
a < 5

array([ True,  True,  True,  True, False, False])

In [49]:
print(np.where(a <=5))

(array([0, 1, 2, 3, 4], dtype=int64),)
